name: base
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - igraph>=0.7.1
  - graph-tool
  - louvain
  - numpy
  - tqdm
  - matplotlib
  - pip
  - pip:
    infomap
    helios
    jgf

